version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/grpc-ecosystem/grpc-gateway/v2
    except:
      - buf.build/googleapis/googleapis
plugins:
  - name: openapiv2
    out: .
    opt:
      - allow_merge=true
      - merge_file_name=examples/internal/proto/examplepb/openapi_merge
